version: "3.9"

services:
    app:
      build:
        context: .
      ports:
        - "8000:8000"
      volumes:
        - ./src:/code
      command: >
        sh -c "python manage.py runserver 0.0.0.0:8000"
    # database:
    #     container_name: postgres
    #     image: postgres:15.0
    #     environment:
    #         - POSTGRES_DB=${POSTGRES_DB}
    #         - POSTGRES_USER=${POSTGRES_USER}
    #         - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    #     ports:
    #         - "${POSTGRES_PORT}:5432"
    #     volumes:
    #         - ./data/db:/var/lib/postgresql/data